### PR TITLE
Clean up some deprecations, bump to 0.7

### PR DESCRIPTION
**Pull request by ajkeller34**

### CODE REVIEW

**Comment by platawiec** [comment]
I'm getting `Warning: Package Clipper does not have Libdl in its dependencies`. Should it be added to REQUIRE?

**Comment by ajkeller34** [comment]
I think something should be tweaked in BinaryBuilder or the use of it here, probably. My understanding is that stdlibs shouldn't go in REQUIRE.

**Comment by ajkeller34** [comment]
Can this be merged? It makes Clipper much less annoying to use on 0.7.

**Comment by jebej** [comment]
It seems like Libdl is included in the project file of LinearAlgebra: https://github.com/JuliaLang/julia/blob/master/stdlib/LinearAlgebra/Project.toml
So maybe it should go in REQUIRE

**Comment by platawiec** [comment]
Project.toml is not quite the same as REQUIRE. I would like a Project.toml for future-proofing reasons, but I would especially like to see this merged :)

**Comment by jebej** [comment]
I fell on this while searching for something unrelated: https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/24

It seems that really all that is needed is to add `using Libdl`

**Comment by jebej** [comment]
I can't edit this PR, but if we merge it I can add the `using` statement right after.

**Comment by jebej** [comment]
bump @SimonDanisch

**Comment by SimonDanisch** [comment]
Sorry I'm somehow not following this repository! Let me have a look!

**Comment by SimonDanisch** [comment]
>I'm getting Warning: Package Clipper does not have Libdl in its dependencies. Should it be added to REQUIRE?

No, you need to call `]resolve`

**Comment by SimonDanisch** [comment]
Thanks for the updates, looks good to me!

**Pull request merged**
